name: 🚀 FTP Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔒 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: ${{ secrets.TARGET_DIR }}
          timeout: 60000
          exclude: |
            **/.git*
            **/.git*/**
            **/.env
            **/node_modules/**
            **/vendor/**
            **/tests/**
            **/storage/logs/**
          dry-run: false
